server:
 port: 9292
spring:
 application:
  name: artist.query.service
 datasource:
  url: jdbc:mysql://192.168.0.21:3307/cqrs 
  # jdbc:mysql://localhost:3306/cqrs run against local MySQL not docker
  username: root
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
 kafka:
  consumer:
   bootstrap-servers: 192.168.0.21:29092
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
   properties:
    spring:
     json:
      trusted:
       packages: com.ltd.coders.software.artist.dto
